### ISSUE TITLE
Added support for argument types in general

### ISSUE THREAD

**Issue by Snooz82** [imbus/robotframework-libdoc2testbench#12]

**Comment by HenrikSchuette** [comment]
Libdoc does sort rf arguments into one of four different classes:
- There are no information about the type of the argument (No type hint).
- The arguments type is a primitive datatype (str, int, float, bool,...)
- The arguments type is a typedDict
- The arguments type is a Enum

**Comment by HenrikSchuette** [comment]
Added in version 1.2.0
