### ISSUE TITLE
added support for default values

### ISSUE THREAD

**Issue by Snooz82** [imbus/robotframework-libdoc2testbench#13]

**Comment by HenrikSchuette** [comment]
Depending on the default value of an robot framework argument different members should be added to the equivalence class of the corresponding TestBench datatype:

- [ ] If the default value is does not yet exist as a member of any of the equivalence classes it is added to the equivalence class with the name of the datatype

**Comment by HenrikSchuette** [comment]
Added in version 1.2.0
