### ISSUE TITLE
Support for different arg types and default values

### ISSUE THREAD

**Issue by Snooz82** [imbus/robotframework-libdoc2testbench#15]
In Python `*` is used for`*varargs` 

The rules for import should be:

- [x] positional only arguments: no special prefix
- [x] positional or keyword args: no special prefix
- [x] variable positional args: '`* `' as prefix (`*${SPACE}`)
- [x] variable positional args do get a default value: `@{EMPTY}`
- [x] named only args: '`- `' as prefix (`-${SPACE}`)
- [x] variable named args: '`** `' as prefix (`**${SPACE}`)
- [x] variable named args do get a default value: `&{EMPTY}`

Given the following keyword:

```python
def my_keyword_with_all_argument_kinds(
    positional_only_argument,
    /,
    positional_or_keyword_argument,
    positional_or_keyword_argument_with_default=42,
    *var_positional_argument,
    keyword_only_argument_with_default=23,
    **var_keyword_argument,
):
```

![image](https://user-images.githubusercontent.com/41592183/216285841-614e6951-0c9b-4a96-a03c-d33872572e32.png)
![image](https://user-images.githubusercontent.com/98702737/216294094-b215e2dd-8feb-4a4c-8490-2a2fc186f233.png)

testbench2robotframework will generate code like this:
(Second Test with defaults)

```robotframework
*** Settings ***
Library    mylib.py


*** Test Cases ***
Test
    My Keyword With All Argument Kinds
    ...   pos_only
    ...   pos_or_kw
    ...   pos_W_def
    ...   var1
    ...   var2
    ...   var3
    ...   keyword_only_argument_with_default=kw_Only
    ...   kwarg_1=kwarg_1
    ...   kwarg_2=kwarg_2
    ...   positional_only_argument=positional_only_argument_but_named

Test 2
    My Keyword With All Argument Kinds
    ...   pos_only
    ...   pos_or_kw
    ...   42
    ...   @{EMPTY}
    ...   keyword_only_argument_with_default=23
    ...   &{EMPTY}
```

**Comment by HenrikSchuette** [comment]
Added in version 1.2.0
