### ISSUE TITLE
Support `--info` argument in CLI

### ISSUE THREAD

**Issue by Snooz82** [imbus/robotframework-libdoc2testbench#4]
If Libdoc2TestBench is called with `--info` it shall print its version together with the version of Robot Framework and Python to the console.

Example:
```
Libdoc2TestBench 1.0.0 [Robot Framework 4.0 (Python 3.9.0 on darwin)]
```

**Comment by Menkeyshow** [comment]
The commit 706ebed6e5abce6cd6bd8eefdb2ad3c6556de565 should resolve this issue.
